Nome = input("Digite seu nome: ")
Idade = input("\nDigite a sua Idade: ")
Email = input("\nDigite o seu Email: ")
Data_de_nascimento = input("\nDigite a sua Data_de_nascimento: ")
Telefone = input("\nDigite o seu Telefone: ")
print("\n--------------------------------------------\n")
print(f"Nome digitado foi: {Nome}")
print(f"\nIdade digitada foi: {Idade}")
print(f"\nEmail digitado foi: {Email}")
print(f"\nData_de_nascimento digitada foi: {Data_de_nascimento}")
print(f"\nTelefone digitado foi: {Telefone}")