from click import clear
t1 = str(input("Digite a tarefa 1: "))
t2 = str(input("Digite a tarefa 2: "))
t3 = str(input("Digite a tarefa 3: "))
t4 = str(input("Digite a tarefa 4:"))
t5 = str(input("Digite a tarefa 5:"))
t6 = str(input("Digite a tarefa 6:"))
t7 = str(input("Digite a tarefa 7:"))
t8 = str(input("Digite a tarefa 8:"))
t9 = str(input("Digite a tarefa 9:"))
t10 =str(input("Digite a tarefa 10:"))
clear()
print('suas tarefas: ')
print(f'tarefa 1: {t1}')
print(f'tarefa 2: {t2}')
print(f'tarefa 3: {t3}')
print(f'tarefa 4: {t4}')
print(f'tarefa 5: {t5}')
print(f'tarefa 6: {t6}')
print(f'tarefa 7: {t7}')
print(f'tarefa 8: {t8}')
print(f'tarefa 9: {t9}')
print(f'tarefa 10: {t10}')